In [1]:
import numpy as np

# One D array

In [2]:
a = [1,2,3]
b = np.array(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[1 2 3]


# Two D array

In [3]:
c = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(c)
print(type(d))
print(d)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(d+2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
d.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Create Numpy Array (arange,zeros,ones,full,eye,rand,randn.randint,linspace)

In [6]:
e = np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [7]:
f = np.arange(0,9,2)
f

array([0, 2, 4, 6, 8])

In [8]:
g = np.zeros((3,3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
h = np.ones((5,5))
h

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
j = np.full([3,4],1)
j

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
k = np.linspace(1,10,3)
k

array([ 1. ,  5.5, 10. ])

In [13]:
import random
np.random.rand(3,3)

array([[0.8085801 , 0.1941977 , 0.98397821],
       [0.87883336, 0.75375251, 0.93786994],
       [0.83998864, 0.83398725, 0.16378084]])

In [14]:
# to include negative values
np.random.randn(3,4)

array([[-0.61729503, -0.15420898, -0.57338041, -0.69380356],
       [ 1.53724466, -0.20892536, -0.99533687, -1.52105654],
       [-0.60425209,  1.36015215, -0.53099396,  1.14338159]])

In [15]:
# only int values
a = np.random.randint(1,9)
b = np.random.randint(1,35,4)
print(a)
print(b)

1
[ 6 12  9 11]


# Array Methods (reshape,min,max,argmax,argmin,shape,size,dtype,astype)

In [16]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
b = np.random.randint(1,50,7)
b

array([49, 13, 48, 46, 10, 34, 36])

In [18]:
c = a.reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# To find min,max and their index

In [19]:
print(b.max())
print(b.min())
print(b.argmax())
print(b.argmin())

49
10
0
4


In [20]:
# Dimension
c.shape

(5, 5)

In [21]:
c.size

25

In [22]:
# Type of datatype
a.dtype

dtype('int32')

In [23]:
# Convert the datatype
c.astype(float)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

# Indexing and Selection

In [24]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
# Selection or Slicing
a[1:3]

array([1, 2])

In [26]:
# Index
a[5]

5

In [27]:
# Broadcasting - Setting values with index range
a[3:6] = 45
a

array([ 0,  1,  2, 45, 45, 45,  6,  7,  8])

In [28]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a[2]

array([7, 8, 9])

In [30]:
a[1][2]

6

In [31]:
a[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
a[a>5]

array([6, 7, 8, 9])

In [33]:
d = np.zeros([10,10])
d_len = d.shape[0]
d_len

10

In [34]:
for i in range(d_len):
    d[i] = i
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [35]:
# Selection
d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [36]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
bool_x = x>5
bool_x

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [38]:
bool_x.dtype

dtype('bool')

# Arithematic Operation

In [39]:
d = np.arange(12)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
d_2 = d + d
d_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [41]:
d_3 = d_2*d
d_3

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162, 200, 242])

In [42]:
new = d_3 - d
new

array([  0,   1,   6,  15,  28,  45,  66,  91, 120, 153, 190, 231])

# Stacking (Horizontal, vertical, column,concatenate)

In [43]:
a = np.array([[1,2],
            [3,4]])

b = np.array([[5,6],
            [7,8]])

print('a', a)
print('b', b)

a [[1 2]
 [3 4]]
b [[5 6]
 [7 8]]


In [44]:
# Vertical Stack
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [45]:
# Horizontal Stack
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
# Column Stack
np.column_stack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [47]:
c = [7,8]
np.column_stack([a,c])

array([[1, 2, 7],
       [3, 4, 8]])

In [48]:
# Concatenate (0 == row wise) and (1 == columnwise)
print('First', np.concatenate([a,b],0))
print('Second', np.concatenate([a,b],1))

First [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Second [[1 2 5 6]
 [3 4 7 8]]


# Splitting

In [49]:
a = np.array([[1,2,3,4],[5,6,7,8],[3,7,9,1],[6,2,9,5]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 7, 9, 1],
       [6, 2, 9, 5]])

In [50]:
# For splitting rows, it must be divide into equal parts. Here, 2 represents the number of splitted arrays
# vsplit - vertical split
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[3, 7, 9, 1],
        [6, 2, 9, 5]])]

In [51]:
# For splitting columns, it must be divide into equal parts. Here, 2 represents the number of splitted arrays
# hsplit - horizontal split
np.hsplit(a,2)

[array([[1, 2],
        [5, 6],
        [3, 7],
        [6, 2]]), array([[3, 4],
        [7, 8],
        [9, 1],
        [9, 5]])]

# Linear Algebra (Rank, Determinant, trace, inverse, power, Solve Linear Algebra)

In [52]:
a = np.random.randn(3,3)
a

array([[ 0.18913318,  0.21458169, -0.33287926],
       [ 0.7304011 , -1.07061777, -1.94781851],
       [ 1.4620295 ,  1.88856968, -0.00991358]])

In [53]:
# Rank (The rank is how many of the rows are "unique": not same as other rows.) (Same for columns.)
print("rank " ,np.linalg.matrix_rank(a))
print("trace ",np.trace(a))
print("determinant ", np.linalg.det(a))
print("inverse " ,np.linalg.inv(a))
print("power ", np.linalg.matrix_power(a, 2))

rank  3
trace  -0.8913981711485182
determinant  -0.8919997516432477
inverse  [[-4.13588077  0.70239751  0.86810858]
 [ 3.18444845 -0.54350274 -0.14042798]
 [-3.30122081  0.04872918  0.40271316]]
power  [[-0.29417724 -0.81781613 -0.47762467]
 [-3.49160544 -2.37563786  1.86154358]
 [ 1.64143772 -1.72693398 -4.16517199]]


In [54]:
b = np.ones([3,3])
c = b.astype(int)
print(b)
print(np.linalg.matrix_rank(c))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1


In [55]:
# Trace  (the sum of elements on the main diagonal (from the upper left to the lower right) of A)
np.trace(c)

3

In [56]:
# Determinant
np.linalg.det(c)

0.0

In [57]:
# Solve Linear Algebra
# x + 3*y = 10
# 2*x + 5*y = 30
# coefficients 
a = np.array([[1, 2], [3, 4]]) 
# constants 
b = np.array([8, 18]) 
print(a)
print(b)

[[1 2]
 [3 4]]
[ 8 18]


In [58]:
print("Solution of linear equations:", np.linalg.solve(a, b))

Solution of linear equations: [2. 3.]


# Reverse, Tile, Repeat, Unique

In [59]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [60]:
a[::-1]

array([[5, 6, 7],
       [3, 4, 5],
       [1, 2, 3]])

In [61]:
# Reverse both row and column with 1 & 3.
a[::-1,::-1]

array([[7, 6, 5],
       [5, 4, 3],
       [3, 2, 1]])

In [62]:
# Repeat & Tile
# Repeat --> repeats each elements as per the number given. first one elements ends then next element starts.
# Tile --> repeats the whole list first and then next will be as per the number given.
a=[1,2,3]
print(np.repeat(a,3))
print(np.tile(a,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [63]:
# Unique & Counts
# The asarray() function is used to convert an given input to an array.
# Input data, in any form that can be converted to an array.
# This includes lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
